name: Action Release Action
description: Release TypeScript action with prebuilt bundle.
author: YUMEMI Inc.
branding:
  icon: tag
  color: green
runs:
  using: node16
  main: 'index.js'
inputs:
  version:
    required: true
    description: Version name of the new release.
  pre-release:
    required: true
    description: Create a pre-release instead.
    default: 'false'
  disable-source-tag:
    required: true
    description: Disable creating a source tag for generating release notes.
    default: 'false'
  release-branch:
    required: true
    description: Branch name to place built artifacts on.
    default: release
  build-command:
    required: true
    description: 'Command(s) to run for building .js file.'
    default: 'pnpm i && pnpm build'
  directory:
    required: true
    description: 'Where the build command generates the artifacts to release.'
    default: 'dist'
  token:
    required: true
    description: GitHub token with contents:write access.
    default: '${{ github.token }}'
